### ISSUE TITLE
ModuleNotFoundError: No module named 'comp_psnr'

### ISSUE THREAD

**Issue by Ran-L** [matri123/IRCNN_deblur_Keras#1]
Dear Author:
I ran your code and got the following error message:

from comp_psnr import comp_quantitative
ModuleNotFoundError: No module named 'comp_psnr'

I don't know if there is some missing code? Thank you very much!

**Comment by matri123** [comment]
Sorry, just remove this line.
Comp_quantitative is implemented in the latter part of the code.
